// Composition de référence HERA — la timeline imposée au départ.
export const DEFAULT_COMPOSITION = {
  "Accueil": [
    { title: "Here Comes The Sun", artist: "The Beatles", year: 1969, duration: "3:05" },
    { title: "Three Little Birds", artist: "Bob Marley", year: 1977, duration: "3:00" },
    { title: "Put Your Records On", artist: "Corinne Bailey Rae", year: 2006, duration: "3:34" },
    { title: "Banana Pancakes", artist: "Jack Johnson", year: 2005, duration: "3:12" },
    { title: "Lovely Day", artist: "Bill Withers", year: 1977, duration: "4:14" },
    { title: "I'm Yours", artist: "Jason Mraz", year: 2008, duration: "4:03" },
    { title: "Budapest", artist: "George Ezra", year: 2013, duration: "3:20" },
    { title: "Valerie", artist: "Mark Ronson & Amy Winehouse", year: 2007, duration: "3:39" },
  ],
  "Cérémonie": [
    { title: "Canon en D", artist: "Pachelbel", year: 1700, duration: "4:30" },
    { title: "Ave Maria", artist: "Schubert", year: 1825, duration: "4:45" },
    { title: "A Thousand Years", artist: "Christina Perri", year: 2011, duration: "4:45" },
    { title: "All of Me", artist: "John Legend", year: 2013, duration: "4:29" },
    { title: "Perfect", artist: "Ed Sheeran", year: 2017, duration: "4:23" },
    { title: "La Vie en rose", artist: "Édith Piaf", year: 1947, duration: "3:07" },
    { title: "Stand By Me", artist: "Ben E. King", year: 1961, duration: "2:58" },
    { title: "Signed, Sealed, Delivered", artist: "Stevie Wonder", year: 1970, duration: "2:39" },
  ],
  "Cocktail": [
    { title: "Feeling Good", artist: "Nina Simone", year: 1965, duration: "2:57" },
    { title: "Fly Me To The Moon", artist: "Frank Sinatra", year: 1964, duration: "2:28" },
    { title: "Sunday Morning", artist: "Maroon 5", year: 2004, duration: "4:04" },
    { title: "Isn't She Lovely", artist: "Stevie Wonder", year: 1976, duration: "6:34" },
    { title: "Sur ma route", artist: "Black M", year: 2014, duration: "3:35" },
    { title: "Get Lucky", artist: "Daft Punk", year: 2013, duration: "4:08" },
    { title: "Cheek to Cheek", artist: "Ella Fitzgerald & Louis Armstrong", year: 1956, duration: "5:39" },
    { title: "Riptide", artist: "Vance Joy", year: 2013, duration: "3:24" },
    { title: "L'Envie", artist: "Johnny Hallyday", year: 1988, duration: "4:26" },
    { title: "Come Away With Me", artist: "Norah Jones", year: 2002, duration: "3:18" },
  ],
  "Dîner": [
    { title: "The Girl From Ipanema", artist: "Stan Getz & João Gilberto", year: 1964, duration: "5:22" },
    { title: "Champs-Élysées", artist: "Joe Dassin", year: 1969, duration: "2:44" },
    { title: "Wonderful Tonight", artist: "Eric Clapton", year: 1977, duration: "3:42" },
    { title: "Something Stupid", artist: "Frank & Nancy Sinatra", year: 1967, duration: "2:44" },
    { title: "Je te promets", artist: "Johnny Hallyday", year: 1986, duration: "4:20" },
    { title: "Your Song", artist: "Elton John", year: 1970, duration: "4:01" },
    { title: "Thinking Out Loud", artist: "Ed Sheeran", year: 2014, duration: "4:41" },
    { title: "La Bohème", artist: "Charles Aznavour", year: 1965, duration: "4:28" },
    { title: "Killing Me Softly", artist: "Roberta Flack", year: 1973, duration: "4:47" },
    { title: "Dernière danse", artist: "Indila", year: 2013, duration: "3:33" },
  ],
  "Ouverture de bal": [
    { title: "At Last", artist: "Etta James", year: 1960, duration: "3:01" },
    { title: "Can't Help Falling in Love", artist: "Elvis Presley", year: 1961, duration: "3:00" },
    { title: "Unchained Melody", artist: "The Righteous Brothers", year: 1965, duration: "3:36" },
    { title: "Je l'aime à mourir", artist: "Francis Cabrel", year: 1979, duration: "4:19" },
    { title: "Time After Time", artist: "Cyndi Lauper", year: 1983, duration: "4:01" },
    { title: "La Tendresse", artist: "Bourvil", year: 1963, duration: "3:12" },
  ],
  "Soirée": [
    { title: "September", artist: "Earth, Wind & Fire", year: 1978, duration: "3:35" },
    { title: "Le Freak", artist: "Chic", year: 1978, duration: "5:29" },
    { title: "Billie Jean", artist: "Michael Jackson", year: 1982, duration: "4:54" },
    { title: "Dancing Queen", artist: "ABBA", year: 1976, duration: "3:51" },
    { title: "Voyage voyage", artist: "Desireless", year: 1986, duration: "4:29" },
    { title: "Joe le taxi", artist: "Vanessa Paradis", year: 1987, duration: "3:44" },
    { title: "Wannabe", artist: "Spice Girls", year: 1996, duration: "2:53" },
    { title: "I Will Survive", artist: "Gloria Gaynor", year: 1978, duration: "3:15" },
    { title: "Alors on danse", artist: "Stromae", year: 2009, duration: "3:26" },
    { title: "Uptown Funk", artist: "Mark Ronson & Bruno Mars", year: 2014, duration: "4:30" },
    { title: "Waka Waka", artist: "Shakira", year: 2010, duration: "3:22" },
    { title: "Levels", artist: "Avicii", year: 2011, duration: "3:19" },
    { title: "Titanium", artist: "David Guetta & Sia", year: 2011, duration: "4:05" },
    { title: "Blinding Lights", artist: "The Weeknd", year: 2019, duration: "3:20" },
    { title: "Djadja", artist: "Aya Nakamura", year: 2018, duration: "2:53" },
    { title: "Bella ciao", artist: "Traditionnel", year: 1945, duration: "2:30" },
  ],
  "Afterparty": [
    { title: "Sweet Caroline", artist: "Neil Diamond", year: 1969, duration: "3:21" },
    { title: "Les Lacs du Connemara", artist: "Michel Sardou", year: 1981, duration: "6:24" },
    { title: "Y.M.C.A.", artist: "Village People", year: 1978, duration: "4:47" },
    { title: "Don't Stop Believin'", artist: "Journey", year: 1981, duration: "4:11" },
    { title: "Mistral gagnant", artist: "Renaud", year: 1985, duration: "4:03" },
    { title: "New York, New York", artist: "Frank Sinatra", year: 1979, duration: "3:26" },
  ],
};
